//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ITeste")]
    public interface ITeste {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeste/Print", ReplyAction="http://tempuri.org/ITeste/PrintResponse")]
        string Print();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeste/Print", ReplyAction="http://tempuri.org/ITeste/PrintResponse")]
        System.Threading.Tasks.Task<string> PrintAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITesteChannel : TestService.ServiceReference1.ITeste, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TesteClient : System.ServiceModel.ClientBase<TestService.ServiceReference1.ITeste>, TestService.ServiceReference1.ITeste {
        
        public TesteClient() {
        }
        
        public TesteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TesteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TesteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TesteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Print() {
            return base.Channel.Print();
        }
        
        public System.Threading.Tasks.Task<string> PrintAsync() {
            return base.Channel.PrintAsync();
        }
    }
}
