// <auto-generated />
namespace Context.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "201401151653193_addUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
