//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestService.ServiceLoL {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pedido", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Pedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EntregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestService.ServiceLoL.ItemPedido[] ItemsPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PrazoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestService.ServiceLoL.StatusPedido StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Entrega {
            get {
                return this.EntregaField;
            }
            set {
                if ((this.EntregaField.Equals(value) != true)) {
                    this.EntregaField = value;
                    this.RaisePropertyChanged("Entrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestService.ServiceLoL.ItemPedido[] ItemsPedido {
            get {
                return this.ItemsPedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsPedidoField, value) != true)) {
                    this.ItemsPedidoField = value;
                    this.RaisePropertyChanged("ItemsPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Prazo {
            get {
                return this.PrazoField;
            }
            set {
                if ((this.PrazoField.Equals(value) != true)) {
                    this.PrazoField = value;
                    this.RaisePropertyChanged("Prazo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestService.ServiceLoL.StatusPedido Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemPedido", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class ItemPedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestService.ServiceLoL.Pedido PedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PedidoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestService.ServiceLoL.Produto ProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProdutoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int quantidadeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestService.ServiceLoL.Pedido Pedido {
            get {
                return this.PedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PedidoField, value) != true)) {
                    this.PedidoField = value;
                    this.RaisePropertyChanged("Pedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PedidoID {
            get {
                return this.PedidoIDField;
            }
            set {
                if ((this.PedidoIDField.Equals(value) != true)) {
                    this.PedidoIDField = value;
                    this.RaisePropertyChanged("PedidoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestService.ServiceLoL.Produto Produto {
            get {
                return this.ProdutoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdutoField, value) != true)) {
                    this.ProdutoField = value;
                    this.RaisePropertyChanged("Produto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProdutoID {
            get {
                return this.ProdutoIDField;
            }
            set {
                if ((this.ProdutoIDField.Equals(value) != true)) {
                    this.ProdutoIDField = value;
                    this.RaisePropertyChanged("ProdutoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                if ((this.quantidadeField.Equals(value) != true)) {
                    this.quantidadeField = value;
                    this.RaisePropertyChanged("quantidade");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusPedido", Namespace="http://schemas.datacontract.org/2004/07/Model.Util")]
    public enum StatusPedido : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AGUARDANDO = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACEITO = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REJEITADO = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ENTREGUE = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ATRASADO = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Produto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestService.ServiceLoL.FornecedorProduto[] FornecedorProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestService.ServiceLoL.ItemPedido[] ItemsPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TamanhoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadeMedidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int quantidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double valorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestService.ServiceLoL.FornecedorProduto[] FornecedorProduto {
            get {
                return this.FornecedorProdutoField;
            }
            set {
                if ((object.ReferenceEquals(this.FornecedorProdutoField, value) != true)) {
                    this.FornecedorProdutoField = value;
                    this.RaisePropertyChanged("FornecedorProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestService.ServiceLoL.ItemPedido[] ItemsPedido {
            get {
                return this.ItemsPedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsPedidoField, value) != true)) {
                    this.ItemsPedidoField = value;
                    this.RaisePropertyChanged("ItemsPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tamanho {
            get {
                return this.TamanhoField;
            }
            set {
                if ((this.TamanhoField.Equals(value) != true)) {
                    this.TamanhoField = value;
                    this.RaisePropertyChanged("Tamanho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadeMedida {
            get {
                return this.UnidadeMedidaField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadeMedidaField, value) != true)) {
                    this.UnidadeMedidaField = value;
                    this.RaisePropertyChanged("UnidadeMedida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                if ((this.quantidadeField.Equals(value) != true)) {
                    this.quantidadeField = value;
                    this.RaisePropertyChanged("quantidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valor {
            get {
                return this.valorField;
            }
            set {
                if ((this.valorField.Equals(value) != true)) {
                    this.valorField = value;
                    this.RaisePropertyChanged("valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FornecedorProduto", Namespace="http://schemas.datacontract.org/2004/07/Model.POCO")]
    [System.SerializableAttribute()]
    public partial class FornecedorProduto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestService.ServiceLoL.Fornecedor FornecedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FornecedorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestService.ServiceLoL.Produto ProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProdutoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValorUnitarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestService.ServiceLoL.Fornecedor Fornecedor {
            get {
                return this.FornecedorField;
            }
            set {
                if ((object.ReferenceEquals(this.FornecedorField, value) != true)) {
                    this.FornecedorField = value;
                    this.RaisePropertyChanged("Fornecedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FornecedorID {
            get {
                return this.FornecedorIDField;
            }
            set {
                if ((this.FornecedorIDField.Equals(value) != true)) {
                    this.FornecedorIDField = value;
                    this.RaisePropertyChanged("FornecedorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestService.ServiceLoL.Produto Produto {
            get {
                return this.ProdutoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdutoField, value) != true)) {
                    this.ProdutoField = value;
                    this.RaisePropertyChanged("Produto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProdutoID {
            get {
                return this.ProdutoIDField;
            }
            set {
                if ((this.ProdutoIDField.Equals(value) != true)) {
                    this.ProdutoIDField = value;
                    this.RaisePropertyChanged("ProdutoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValorUnitario {
            get {
                return this.ValorUnitarioField;
            }
            set {
                if ((this.ValorUnitarioField.Equals(value) != true)) {
                    this.ValorUnitarioField = value;
                    this.RaisePropertyChanged("ValorUnitario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fornecedor", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Fornecedor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CnpjField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestService.ServiceLoL.FornecedorProduto[] FornecedorProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestService.ServiceLoL.Pedido[] PedidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazaoSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cnpj {
            get {
                return this.CnpjField;
            }
            set {
                if ((object.ReferenceEquals(this.CnpjField, value) != true)) {
                    this.CnpjField = value;
                    this.RaisePropertyChanged("Cnpj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Endereco {
            get {
                return this.EnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true)) {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestService.ServiceLoL.FornecedorProduto[] FornecedorProduto {
            get {
                return this.FornecedorProdutoField;
            }
            set {
                if ((object.ReferenceEquals(this.FornecedorProdutoField, value) != true)) {
                    this.FornecedorProdutoField = value;
                    this.RaisePropertyChanged("FornecedorProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestService.ServiceLoL.Pedido[] Pedidos {
            get {
                return this.PedidosField;
            }
            set {
                if ((object.ReferenceEquals(this.PedidosField, value) != true)) {
                    this.PedidosField = value;
                    this.RaisePropertyChanged("Pedidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazaoSocial {
            get {
                return this.RazaoSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazaoSocialField, value) != true)) {
                    this.RazaoSocialField = value;
                    this.RaisePropertyChanged("RazaoSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefone {
            get {
                return this.TelefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneField, value) != true)) {
                    this.TelefoneField = value;
                    this.RaisePropertyChanged("Telefone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceLoL.IWsPedidos")]
    public interface IWsPedidos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsPedidos/GetAll", ReplyAction="http://tempuri.org/IWsPedidos/GetAllResponse")]
        TestService.ServiceLoL.Pedido[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsPedidos/GetAll", ReplyAction="http://tempuri.org/IWsPedidos/GetAllResponse")]
        System.Threading.Tasks.Task<TestService.ServiceLoL.Pedido[]> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsPedidosChannel : TestService.ServiceLoL.IWsPedidos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsPedidosClient : System.ServiceModel.ClientBase<TestService.ServiceLoL.IWsPedidos>, TestService.ServiceLoL.IWsPedidos {
        
        public WsPedidosClient() {
        }
        
        public WsPedidosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsPedidosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsPedidosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsPedidosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestService.ServiceLoL.Pedido[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<TestService.ServiceLoL.Pedido[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
    }
}
